@echo off
REM AUTOGENERATED by wms_ui.py for scheduled task: WMS_Export_1000_DAILY
REM Edit the schedule through the WMS UI, not this file.
cd /d "C:\Users\ZTE\Desktop\Python\WMS CLARA export"
"C:\Users\ZTE\AppData\Local\Programs\Python\Python313\pythonw.exe" "C:\Users\ZTE\Desktop\Python\WMS CLARA export\_scheduled_run.py" 
